CREATE TYPE "Role" AS ENUM ('ADMIN','OPERATIONS_MANAGER','SUPPORT_AGENT','WAREHOUSE_MANAGER');
CREATE TYPE "OrderStatus" AS ENUM ('PROCESSING','PACKED','SHIPPED','DELIVERED','FAILED','CANCELLED');
CREATE TYPE "PaymentStatus" AS ENUM ('PAID','PENDING','FAILED','REFUNDED');
CREATE TYPE "AlertSeverity" AS ENUM ('INFO','WARNING','CRITICAL','RESOLVED');
CREATE TYPE "RefundStatus" AS ENUM ('PENDING','APPROVED','PROCESSING','COMPLETED','FAILED');

CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"email" TEXT NOT NULL UNIQUE,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "RefreshToken" ("id" TEXT PRIMARY KEY,"tokenHash" TEXT NOT NULL UNIQUE,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Order" ("id" TEXT PRIMARY KEY,"customerName" TEXT NOT NULL,"customerEmail" TEXT NOT NULL,"amount" INTEGER NOT NULL,"status" "OrderStatus" NOT NULL,"paymentStatus" "PaymentStatus" NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "OrderItem" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"sku" TEXT NOT NULL,"price" INTEGER NOT NULL,"quantity" INTEGER NOT NULL,"orderId" TEXT NOT NULL REFERENCES "Order"("id") ON DELETE CASCADE);
CREATE TABLE "Warehouse" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"city" TEXT NOT NULL);
CREATE TABLE "Product" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"sku" TEXT NOT NULL UNIQUE,"category" TEXT NOT NULL,"price" INTEGER NOT NULL);
CREATE TABLE "Inventory" ("id" TEXT PRIMARY KEY,"quantity" INTEGER NOT NULL,"productId" TEXT NOT NULL REFERENCES "Product"("id") ON DELETE CASCADE,"warehouseId" TEXT NOT NULL REFERENCES "Warehouse"("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "Inventory_productId_warehouseId_key" ON "Inventory"("productId","warehouseId");
CREATE TABLE "Alert" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"message" TEXT NOT NULL,"severity" "AlertSeverity" NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Refund" ("id" TEXT PRIMARY KEY,"orderId" TEXT NOT NULL REFERENCES "Order"("id"),"userId" TEXT NOT NULL REFERENCES "User"("id"),"amount" INTEGER NOT NULL,"reason" TEXT NOT NULL,"status" "RefundStatus" NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "FeatureFlag" ("id" TEXT PRIMARY KEY,"key" TEXT NOT NULL UNIQUE,"description" TEXT,"enabled" BOOLEAN NOT NULL DEFAULT false);
